### ISSUE TITLE
Lesson 11. Clothes

### ISSUE THREAD

**Issue by milkina** [Aleksey25/HomeWork#4]
1. Skirt. dressWomen, Tie.dressMan,Trousers.dressMan, Trousers.dressWomen,Tshort.dressWomen, Tshort.dressMan - выведите какое-то сообщение на консоль.
2. Trousers - нет смысла переопределять геттеры и сеттеры. Уберите их.

**Comment by Aleksey25** [comment]
Исправил

**Comment by milkina** [comment]
Пункт 2 не выполнен.

**Comment by Aleksey25** [comment]
FIXED
