### ISSUE TITLE
Lesson 9. Task 2. Car.

### ISSUE THREAD

**Issue by milkina** [Aleksey25/HomeWork#5]
1. Класс Engine, Driver - переменные должны иметь модификатор доступа private.
2. В методе printInfo используйте toString  метод. 
3. Методы toString  классов Lorry and SportCar сейчас не содержат инфо класса Car. Добавьте ее используя super.

**Comment by milkina** [comment]
Пункт 2 не выполнен.

**Comment by Aleksey25** [comment]
Исправил

**Comment by milkina** [comment]
1. Car - неотформатирован.
2. Вместо  System.out.println(toString()); лучше писать   System.out.println(this);
3. И вообще, так как мы уже изучили метод printInfo, его можно убрать и распечатывать инфо как System.out.println(car1); вместо car1.printInfo();
4.  У вас же в printInfo было переведено на русский язык, можно было это перенести в toString()

**Comment by Aleksey25** [comment]
Исправил

**Comment by milkina** [comment]
Методы printInfo, printSport, printLorry вы не используете, вместо них используется toString().  Их можно убрать. 
Или хотя бы уберите комментарии из printSport, printLorry.

**Comment by Aleksey25** [comment]
Убрал лишние методы
